print('Enter first number')
num1 = int(input())
print('Enter second number')
num2 = int(input())
print('Enter third number')
num3 = int(input())
print('Sum of three nubers is '+ str(num1 + num2 + num3))
